database:
  # main DB type
  active: mysql

spring:
  # main DB (mariaDB 변경)
  datasource1:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/HAPPYCALL4?useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useSSL=false
    username: minds
    password: msl1234~
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  datasource2:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/Chatbot?useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useSSL=false
    username: minds
    password: msl1234~
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  batch:
    initialize-schema: never
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

websocket:
  protocol: wss
  ip: localhost
  port: ':13254'

audio:
  ip: localhost
  port: ':15000'

rest:
  ip: localhost
  port: ':15000'
  ssl: false

voice:
  ip: localhost
  port: ':5800'

proxy:
  protocol: ws
  ip: 10.50.1.19
  port: ':18080'

chatting:
  ip: localhost
  port: ':50000'

excel:
  form:
    path: '/home/minds/maum/fast/excel/'
  upload:
    path: '/home/minds/maum/fast/excel/happycall_webfile/'

mail-info:
  username: 'mailtest0218'
  password: 'a123456789!'
  port: 465
  host: 'smtp.gmail.com'
  Internet-address: 'mailtest0218@gmail.com'

obcalltotal:
  ip: localhost
  port: ':15002'
  protocol: '/call_stat'

solr:
  url: 'http://localhost:18983/solr/mrc'
  en_url: 'http://localhost:18983/solr/mrc_en'

domain: http://10.50.1.19:18080/

cookie:
  domainName: 10.50.1.19

autocall:
  is-execute: true
  batch-interval-time: 10
  check-valid-url: ''

msgtalk:
  is-execute: false
  batch-interval-time: '0 0 10 * * *'
  check-valid-url: ''

#현대해상 : hdhs, maum-ai: maumAi
site-custom: 'maumAi'

iframe_url:
  simplebot: 'http://10.50.1.19:18090/sds-builder/upload/simpleBot'
  chatbotBuilder: 'http://10.50.1.19:18090/sds-builder/upload/chatbotBuilder'
  voicebotBuilder: 'http://10.50.1.19:18090/sds-builder/upload/vbBuilder'

#iframe_url:
#  simplebot: 'http://10.50.1.19/upload/simpleBot'
#  chatbotBuilder: 'http://10.50.1.19/upload/chatbotBuilder'
#  voicebotBuilder: 'http://10.50.1.19/upload/vbBuilder'

api:
  simplebot:
    get_list_url: 'http://10.50.1.19:sds-builder/upload/simpleBot/getSimpleBotList'

# JWT signKey
maum:
  SigningKey:

sso:
  mindslab:
    client-id:
    request:
      authorize:
        url:
      request-token:
        url:
      logout-token:
        url:
      maum-login:
        url:
    callback:
      token:
        url:
    companyId:
    companyGroupId:

# PW Change month
pw-month: 3
# PW Error max
pw-err-max: 5

#사이트에 맞게 수정
logging:
  file:
    fast: /
    da: /
    cm: /
    sds: /
  name:
    fast: log.log
    da: log.log
    cm: log.log
    sds: log.log
  maxThread : 3
#작업의뢰 form,upload 경로 설정
work-request:
  form:
    path: '/home/minds/maum/fast/excel/work-request/form/'
  upload:
    path: '/home/minds/maum/fast/excel/work-request/upload/'