database:
  # main DB type
  active: mysql

spring:
  # main DB (mariaDB 변경)
  datasource1:
    jdbc-url: jdbc:log4jdbc:mysql://maumai-db:9004/HAPPYCALL4?useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useSSL=false
    username: minds
    password: msl1234~
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  datasource2:
    jdbc-url: jdbc:log4jdbc:mysql://maumai-db:9004/Chatbot?useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useSSL=false
    username: minds
    password: msl1234~
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  batch:
    initialize-schema: never
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

websocket:
  protocol: wss
  ip: fast-aicc-dev.maum.ai
  port: ':13254'

audio:
  ip: fast-aicc-dev.maum.ai
  port: ':15000'

rest:
  ip: fast-aicc-dev.maum.ai
  port: ':15000'
  ssl: false

voice:
  ip: fast-aicc-dev.maum.ai
  port: ':5800'

proxy:
  protocol: wss
  ip: fast-aicc-dev.maum.ai
  port: ':443'

chatting:
  ip: fast-aicc-dev.maum.ai
  port: ':50000'

excel:
  form:
    path: '/home/minds/fast/excel/'
  upload:
    path: '/home/minds/fast/excel/happycall_webfile/'

mail-info:
  username: 'mailtest0218'
  password: 'a123456789!'
  port: 465
  host: 'smtp.gmail.com'
  Internet-address: 'mailtest0218@gmail.com'

obcalltotal:
  ip: localhost
  port: ':15002'
  protocol: '/call_stat'

solr:
  url: 'http://localhost:18983/solr/mrc'
  en_url: 'http://localhost:18983/solr/mrc_en'

domain: https://fast-aicc-dev.maum.ai/

cookie:
  domainName: maum.ai

autocall:
  is-execute: true
  batch-interval-time: 10
  check-valid-url: ''

msgtalk:
  is-execute: false
  batch-interval-time: '0 0 10 * * *'
  check-valid-url: ''

site-custom: 'maumAi'

iframe_url:
  simplebot: 'https://sds-dev.maum.ai:8080/sds-builder/upload/simpleBot'
  chatbotBuilder: 'https://sds-dev.maum.ai:8080/sds-builder/upload/chatbotBuilder'
  voicebotBuilder: 'https://sds-dev.maum.ai:8080/sds-builder/upload/vbBuilder'

api:
  simplebot:
    get_list_url: 'https://sds-dev.maum.ai:8080/sds-builder/upload/simpleBot/getSimpleBotList'

# JWT signKey
maum:
  SigningKey: MindsLABMAUMAccountManagementSystemAMS1234567890

sso:
  mindslab:
    client-id: fast-aicc
    request:
      authorize:
        url: http://localhost/hq/oauth/authorize
      request-token:
        url: http://localhost/hq/oauth/token
      logout-token:
        url: http://localhost/logout
      maum-login:
        url: http://localhost/auth/login?redirect_url=https://fast-aicc-dev.maum.ai/login
    callback:
      token:
        url: https://fast-aicc-dev.maum.ai/login
    companyId: comp007 #추후 수정 필요
    companyGroupId: 2 #추후 수정 필요

# PW Change month
pw-month: 3
# PW Error max
pw-err-max: 5

#사이트에 맞게 수정
logging:
  file:
    fast: /
    da: /
    cm: /
    sds: /
  name:
    fast: log.log
    da: log.log
    cm: log.log
    sds: log.log
  maxThread : 3
#작업의뢰 form,upload 경로 설정
work-request:
  form:
    path: '/home/minds/fast/excel/work-request/form/'
  upload:
    path: '/home/minds/fast/excel/work-request/upload/'